version: "3.8"
services:
  react-nginx: 
    container_name: react-nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html
    ports:
      - 80:80
    