version: 2.1

orbs:
  node: circleci/node@5.1.0
jobs: 
  build-and-push: 
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
        steps:
        - checkout
        

workflows:
  my-workflow: 
    jobs:
      - node/test
      - build-and-push:
        filters: 
          requires:
            - node/test            
          branches: 
            only: 
            - main

