version: 2.1

orbs:
  node: circleci/node@5.1.0
jobs: 
  test: 
    docker:
      - image: cimg/node:16.19
    steps:     
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
      # Checkout the code as the first step.
      - checkout
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages:
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
      - run: npm test

  build-and-deploy: 
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps: 
      - checkout      
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            cat /etc/os-release
            sudo apt-get update -y 
            sudo apt install gnome-terminal -y 
            rm -r $HOME/.docker/desktop
            sudo rm /usr/local/bin/com.docker.cli
            sudo apt-get purge docker-desktop -y 
            sudo apt-get update
            sudo apt-get install \
              ca-certificates \
              curl \
              gnupg \
              lsb-release -y 
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update -y 
            sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y 
            sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
     
      - run: |
          TAG=$CIRCLE_BUILD_NUM
          IMAGE_NAME=react-cicd
          docker build -t mthang1801/react-cicd:latest .
          docker login -u $DOCKER_USERNAME -p DOCKER_PASSWORD
          docker push mthang1801/react-cicd:latest

workflows:
  build-test-deploy: 
    jobs:
      - test: 
          filters:                
            branches: 
              only: main
      - build-and-deploy:
          requires:
            - test  
          filters:                
            branches: 
              only: main

