version: 2.1

orbs:
  node: circleci/node@5.1.0
jobs: 
  test: 
    docker:
      - image: cimg/node:16.19
    steps:     
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
      # Checkout the code as the first step.
      - checkout
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages:
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
      - run: npm test

  build-push-image: 
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps: 
      - checkout      
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      # - run:
      #     name: Build service
      #     command: make
      - run: |
          TAG=$CIRCLE_BUILD_NUM
          IMAGE_NAME=react-cicd        
          docker build -t $IMAGE_NAME:latest .                     
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag $IMAGE_NAME:latest $DOCKER_USER/$IMAGE_NAME:$TAG
          docker push $DOCKER_USER/$IMAGE_NAME:$TAG
          docker rmi $IMAGE_NAME:latest
          docker rmi $DOCKER_USER/$IMAGE_NAME:$TAG

  deploy:    
    docker: 
      - image: cimg/base:2022.09
    steps: 
      - add_ssh_keys:
          fingerprints:
            - "48:a2:03:63:40:3c:36:1e:66:60:8c:24:1b:2f:60:1b"
      - run: 
          name: "Deploy over SSH" 
          command: |
            ssh react-cicd@15.235.207.51 "cat /etc/os-release"
  
workflows:
  build-test-deploy: 
    jobs:
      - test: 
          filters:                
            branches: 
              only: main
      - build-push-image:
          requires:
            - test  
          filters:                
            branches: 
              only: main
      - deploy: 
          requires:
            - build-push-image
          filters:                
            branches: 
              only: main

